// AUTO-GENERATED by scripts/sync-version.ps1 -- do not edit by hand.
// The source of truth is [workspace.package] version in the root Cargo.toml.
public enum BuildInfo {
    public static let version = "1.0.0"
}
