; ============================================================================
;  nospacekey.iss -- Inno Setup script for the nospacekey Windows IME (SP6c).
;
;  WHAT THIS DOES
;    Installs the staged self-contained distribution tree (produced by
;    scripts\stage-dist.ps1 into ..\dist) per-machine into Program Files and
;    registers the TSF text-input processor (TIP) DLL.
;
;    Registration is performed by Inno's "regserver" flag on nospacekey_tip.dll:
;      - on INSTALL   Setup calls the DLL's DllRegisterServer   (== regsvr32 /s)
;      - on UNINSTALL Setup calls the DLL's DllUnregisterServer  (== regsvr32 /u /s)
;    This reuses the EXISTING, unmodified register.rs path: DllRegisterServer
;    writes HKCR\CLSID\InprocServer32 and performs the imperative COM
;    RegisterProfile / RegisterCategory calls (KEYBOARD / IMMERSIVESUPPORT /
;    UIELEMENTENABLED). DllUnregisterServer reverses it (UnregisterProfile +
;    CLSID tree removal) for a clean uninstall. No source changes are needed.
;
;  ENGINE STOP ON UNINSTALL / UPGRADE
;    The persist engine (NospacekeyEngineHost.exe) does NOT exit on its own, so it
;    would otherwise survive uninstall/upgrade and lock its exe (zombie + stale
;    files). UNINSTALL stops it in two steps: (1) graceful -- NospacekeyConfig.exe
;    --stop-engine sends a Shutdown IPC so the engine flushes learning and exits;
;    (2) sweep -- elevated taskkill /F for other sessions or graceful failures.
;    UPGRADE ([Code] PrepareToInstall) uses taskkill only, for both the engine and
;    the config GUI, before file replacement -- graceful is NOT used on upgrade
;    because {app}'s config is still the OLD one there and a {tmp}-extracted new
;    config cannot load its VCRUNTIME deps on a clean machine (see PrepareToInstall).
;    Killing the config also prevents an in-use NospacekeyConfig.exe from Abort/Retry
;    stranding the old config. The upgrade cost is only the RAM learning of a
;    composition in progress at that instant (committed learning is already on disk).
;    In-use PEs (TIP DLL, and the engine exe if respawned mid-copy) fall back to
;    reboot-time replacement via restartreplace; any engine lingering until reboot
;    is reclaimed by the TIP's proto version handshake.
;
;  WHY admin / per-machine
;    A TSF TIP must be registered per-machine (HKLM; CLASSES_ROOT == HKLM),
;    which requires elevation. PrivilegesRequired=admin enforces this.
;
;  HOW TO BUILD (this dev box has NO ISCC -- do this on a VM/host with Inno Setup)
;    Normally run scripts\release.ps1 instead (one command; evidence-gated order).
;    The manual steps below are the fallback decomposition:
;    1. Stage the payload:        powershell -File scripts\stage-dist.ps1 -Rebuild
;    2. Sign the payload PEs:     powershell -File scripts\sign-dist.ps1
;                                 (signs dll/exe + bundled llama/ggml DLLs BEFORE
;                                  they are packed into the installer)
;    3. Compile the installer:    ISCC installer\nospacekey.iss
;                                 -> produces installer\Output\nospacekey-setup.exe
;    4. Sign the produced setup:  powershell -File scripts\sign-dist.ps1 -SetupExe installer\Output\nospacekey-setup.exe
;
;  The same pipeline swaps the dev self-signed cert for a real OV cert by
;  passing -Thumbprint to sign-dist.ps1; this .iss is unaffected.
; ============================================================================

#define MyAppName "nospacekey"
; MyAppVersion lives in version.iss (generated by scripts/sync-version.ps1) so the
; installer version stays in lockstep with the root Cargo.toml single source.
#include "version.iss"
#define MyAppPublisher "nospacekey project contributors"

; --- Zenzai model download constants -------------------------------------
; REQUIRES Inno Setup 6.3.0+ : this file contains Japanese strings and is
; saved as UTF-8 WITHOUT a BOM, which older ISCC interprets as ANSI (mojibake).
; SINGLE SOURCE = crates/config/src/download.rs (MODEL_FILENAME / MODEL_URL /
; MODEL_SHA256). crates/config/tests/model_constants_consistency.rs asserts
; these three literals match; update BOTH files together or the test goes RED.
; The .gguf is fetched from the origin (HuggingFace) at install time and is
; NEVER bundled -- bundling would make this installer a CC-BY-SA-4.0
; redistributor (see docs/superpowers/specs/2026-07-16-installer-zenzai-
; download-design.md).
#define ModelFileName "ggml-model-Q5_K_M.gguf"
#define ModelDownloadURL "https://huggingface.co/Miwa-Keita/zenz-v3.1-small-gguf/resolve/main/ggml-model-Q5_K_M.gguf"
#define ModelSHA256 "4de930c06bef8c263aa1aa40684af206db4ce1b96375b3b8ed0ea508e0b14f6c"

[Setup]
; Fix the update identity. The current script has NO AppId (== AppName default),
; so pin AppId=nospacekey to match existing dev installs. Doing it before public
; distribution is the cheapest moment; if the naming decision later changes
; AppName, AppId can stay put -- that is the whole point of pinning it now.
AppId=nospacekey
AppName={#MyAppName}
AppVersion={#MyAppVersion}
; Stamp the produced setup.exe's own VERSIONINFO resource with the same version.
VersionInfoVersion={#MyAppVersion}
AppPublisher={#MyAppPublisher}
DefaultDirName={autopf}\nospacekey
DefaultGroupName=nospacekey
; TSF TIP registration is per-machine (HKLM) -> elevation required.
PrivilegesRequired=admin
; 64-bit only distribution (the TIP DLL and engine are x86_64).
ArchitecturesAllowed=x64compatible
ArchitecturesInstallIn64BitMode=x64compatible
LicenseFile=..\LICENSE
OutputBaseFilename=nospacekey-setup
Compression=lzma2
SolidCompression=yes
UninstallDisplayName=nospacekey IME
WizardStyle=modern
; The TIP DLL is held by EVERY app that loaded the IME. Do NOT let Restart
; Manager try to close them all (CloseApplications default is yes); instead the
; in-use DLL/exe are swapped at reboot via restartreplace (see [Files]).
CloseApplications=no

[Tasks]
; Zenzai (neural conversion) opt-out download (~70 MB, from HuggingFace).
; Default-checked: settings default to zenzai.enabled=true and the engine
; auto-resolves {app}\models\{#ModelFileName} (ZenzaiConfig.resolve), so
; placing the file is ALL that is needed -- no settings write, no toggle.
; Unchecked / offline / failed => classic conversion; the model can still be
; fetched later from the settings GUI (its LOCALAPPDATA + weight_path path).
Name: "zenzaimodel"; Description: "Zenzai（ニューラル変換）を使用する — 約70MBのモデルをダウンロード（推奨）"

[Files]
; --- The TIP DLL gets its OWN line so Inno calls DllRegisterServer on install
;     and DllUnregisterServer on uninstall. It is EXCLUDED from the recurse
;     line below so it is placed only here (with the regserver flag).
;     restartreplace + uninsrestartdelete: the DLL is loaded by every app using
;     the IME, so an in-use copy on update/uninstall falls back to a reboot-time
;     replace/delete instead of Abort/Retry. ---
Source: "..\dist\nospacekey_tip.dll"; DestDir: "{app}"; Flags: regserver 64bit ignoreversion restartreplace uninsrestartdelete

; --- The engine exe gets its own line with restartreplace. The stop step in
;     PrepareToInstall / [UninstallRun] kills the running engine, but a surviving
;     TIP host's next-keystroke ensure_engine or power-resume prewarm can respawn
;     the OLD exe in the window between stop and file-copy. With CloseApplications=no
;     there is no Restart Manager rescue, so without restartreplace an in-use copy
;     would Abort/Retry. restartreplace turns that into "replace at reboot; the
;     lingering old engine until then is reclaimed by the TIP proto handshake". ---
Source: "..\dist\NospacekeyEngineHost.exe"; DestDir: "{app}"; Flags: 64bit ignoreversion restartreplace

; --- Everything else in the staged tree: the config exe (NospacekeyConfig.exe), the
;     three *.resources bundles (dictionary / tokenizer / hub), ~32 Swift runtime
;     DLLs, the bundled llama/ggml DLLs, models\README.txt, LICENSE and
;     THIRD-PARTY-NOTICES.md. Recurse all subdirs, but do NOT re-place the TIP DLL /
;     engine exe (handled by the dedicated lines above). ---
Source: "..\dist\*"; DestDir: "{app}"; Flags: recursesubdirs createallsubdirs ignoreversion; Excludes: "nospacekey_tip.dll,NospacekeyEngineHost.exe"

[Icons]
; Shortcut to the settings GUI (SP6b) and to the third-party notices.
Name: "{group}\nospacekey Settings"; Filename: "{app}\NospacekeyConfig.exe"
Name: "{group}\Third-Party Notices"; Filename: "{app}\THIRD-PARTY-NOTICES.md"
Name: "{group}\Uninstall nospacekey"; Filename: "{uninstallexe}"

[UninstallDelete]
; The Zenzai model is placed by [Code] (download), NOT by [Files], so the
; uninstaller does not track it. Without these lines a 70 MB .gguf survives
; uninstall, keeps {app}\models (and thus {app}) from being removed, and
; violates the v1.0 DoD "uninstall leaves no trace".
Type: files; Name: "{app}\models\{#ModelFileName}"
Type: dirifempty; Name: "{app}\models"

[Run]
; Optional: open the settings GUI right after install so the user can enable
; the external LLM / pick a model. Unchecked by default; skippable in silent.
Filename: "{app}\NospacekeyConfig.exe"; Description: "Open nospacekey settings"; Flags: postinstall nowait skipifsilent unchecked

[UninstallRun]
; Two-step engine stop on uninstall (no zombie process left holding the exe/DLL).
; 1) graceful: flush learning and let the engine exit itself (current session).
Filename: "{app}\NospacekeyConfig.exe"; Parameters: "--stop-engine"; Flags: runhidden waituntilterminated; RunOnceId: "StopEngineGraceful"
; 2) sweep: other user sessions / graceful failures. Elevated -> reaches all sessions.
;    Absent-process exit code 128 is ignored ([UninstallRun] ignores failures by default).
Filename: "{cmd}"; Parameters: "/C taskkill /F /IM NospacekeyEngineHost.exe /T"; Flags: runhidden waituntilterminated; RunOnceId: "StopEngineForce"
Filename: "{cmd}"; Parameters: "/C taskkill /F /IM NospacekeyConfig.exe"; Flags: runhidden waituntilterminated; RunOnceId: "StopConfigForce"

[Code]
var
  DownloadPage: TDownloadWizardPage;
  // ssPostInstall へ「検証済みモデルが {tmp} に居る」ことを運ぶフラグ。
  // (タスク未選択・スキップ・失敗のとき ssPostInstall が {tmp} を触らないための門)
  ModelFetched: Boolean;

function ModelDestPath(): String;
begin
  Result := ExpandConstant('{app}\models\{#ModelFileName}');
end;

procedure InitializeWizard();
begin
  DownloadPage := CreateDownloadPage(SetupMessage(msgWizardPreparing), SetupMessage(msgPreparingDesc), nil);
  DownloadPage.ShowBaseNameInsteadOfUrl := True;
end;

function NextButtonClick(CurPageID: Integer): Boolean;
begin
  Result := True;
  // wpReady 時点なら {app} は確定済み(ディレクトリ選択ページ通過後 / 更新時はレジストリ解決)。
  // 既存モデルがあれば再取得しない(更新インストールで 70MB を引き直さない)。
  if (CurPageID = wpReady) and WizardIsTaskSelected('zenzaimodel')
     and (not FileExists(ModelDestPath())) then begin
    DownloadPage.Clear;
    DownloadPage.Add('{#ModelDownloadURL}', '{#ModelFileName}', '{#ModelSHA256}');
    DownloadPage.Show;
    try
      try
        // DownloadTemporaryFile が SHA256 を検証(不一致は例外)。保存先は {tmp}。
        DownloadPage.Download;
        ModelFetched := True;
      except
        // 非致命: 従来変換で続行。silent では Suppressible が既定応答(IDOK)で流れる。
        // ユーザー自身の Abort に「失敗しました」ダイアログを重ねない(ログのみ)。
        if DownloadPage.AbortedByUser then
          Log('Zenzai model download aborted by user.')
        else begin
          Log('Zenzai model download failed: ' + GetExceptionMessage);
          SuppressibleMsgBox(
            'Zenzai モデルのダウンロードに失敗しました。従来変換でインストールを続行します。'
            + #13#10 + 'モデルは後から nospacekey 設定画面（変換エンジン）で取得できます。',
            mbInformation, MB_OK, IDOK);
        end;
      end;
    finally
      DownloadPage.Hide;
    end;
  end;
end;

procedure CurStepChanged(CurStep: TSetupStep);
begin
  // ssPostInstall = [Files] 展開後なので {app}\models\ (dist の README.txt で作成済み) が実在。
  // ForceDirectories は dist 構成が変わっても DL 成功分を黙って捨てないための保険。
  // {tmp} 経由の 2 段構えにより、失敗時に {app} へ半端ファイルが残ることはない。
  if (CurStep = ssPostInstall) and ModelFetched then begin
    ForceDirectories(ExpandConstant('{app}\models'));
    if not CopyFile(ExpandConstant('{tmp}\{#ModelFileName}'), ModelDestPath(), False) then
      Log('Zenzai model copy to {app}\models failed');
  end;
end;

function PrepareToInstall(var NeedsRestart: Boolean): String;
var R: Integer;
begin
  // Update install: stop the old engine AND the old config GUI BEFORE replacing
  // files. taskkill both (not graceful), because:
  //  (F-A) the graceful path must run the NEW config, but {app}'s config is still
  //        the OLD one here (files not copied yet), and running the new config from
  //        {tmp} via ExtractTemporaryFile fails to LOAD on a clean machine -- the
  //        config exe statically imports VCRUNTIME140/140_1.dll, which are installed
  //        into {app} (from dist) but are NOT beside a {tmp}-extracted exe, so the
  //        loader errors before --stop-engine even runs. (Running {app}'s OLD config
  //        is also out: its pre-this-change main.rs parse-and-ignores argv and opens
  //        a hidden Tauri GUI that blocks the installer forever.)
  //  (F-B) killing the config GUI here prevents an in-use NospacekeyConfig.exe from
  //        causing an Abort/Retry whose Ignore would strand the OLD config in {app}
  //        and later hang the uninstaller's graceful --stop-engine step.
  // The graceful learning-flush still happens on UNINSTALL ([UninstallRun]
  // StopEngineGraceful runs {app}'s NEW config, deps co-located). The only upgrade
  // cost is the RAM learning of a composition in progress at this instant; committed
  // learning is already flushed to disk at each endSession and is untouched here.
  Exec(ExpandConstant('{cmd}'), '/C taskkill /F /IM NospacekeyEngineHost.exe /T', '', SW_HIDE, ewWaitUntilTerminated, R);
  Exec(ExpandConstant('{cmd}'), '/C taskkill /F /IM NospacekeyConfig.exe', '', SW_HIDE, ewWaitUntilTerminated, R);
  Result := '';
end;
