; ============================================================================
;  nospacekey.iss -- Inno Setup script for the nospacekey Windows IME (SP6c).
;
;  WHAT THIS DOES
;    Installs the staged self-contained distribution tree (produced by
;    scripts\stage-dist.ps1 into ..\dist) per-machine into Program Files and
;    registers the TSF text-input processor (TIP) DLL.
;
;    Setup explicitly supervises DllRegisterServer so a failed upgrade can put
;    the validated retained TIP back. The DLL registers its profile/categories
;    before committing InprocServer32; per-file automatic rollback cannot
;    preserve a shared CLSID across side-by-side versions. Rollback executes only
;    the newly shipped DLL and passes the retained path as hex-encoded data.
;
;  SIDE-BY-SIDE UPGRADES
;    Every release is copied to {app}\versions\<product-version>. The registered
;    COM target moves to the new TIP, while applications that already loaded the
;    old DLL retain its sibling EngineHost and versioned pipe. Upgrade never kills
;    an old engine and never replaces a loaded binary. Old trees are intentionally
;    retained. Safe lifetime-aware reclamation is tracked separately in #45.
;
;  WHY admin / per-machine
;    A TSF TIP must be registered per-machine (HKLM; CLASSES_ROOT == HKLM),
;    which requires elevation. PrivilegesRequired=admin enforces this.
;
;  HOW TO BUILD (ISCC is user-scope installed at %LOCALAPPDATA%\Programs\Inno Setup 6;
;    release.ps1 discovers it, while manual ISCC invocation may prepend it to PATH)
;    Normally run scripts\release.ps1 instead (one command; evidence-gated order).
;    The manual steps below are the fallback decomposition:
;    1. Stage the payload:        powershell -File scripts\stage-dist.ps1 -Rebuild
;    2. Sign the payload PEs:     powershell -File scripts\sign-dist.ps1
;                                 (signs dll/exe + bundled llama/ggml DLLs BEFORE
;                                  they are packed into the installer)
;    3. Compile the installer:    ISCC installer\nospacekey.iss
;                                 -> produces installer\Output\nospacekey-setup.exe
;    4. Sign the produced setup:  powershell -File scripts\sign-dist.ps1 -SetupExe installer\Output\nospacekey-setup.exe
;
;  The same pipeline swaps the dev self-signed cert for a real OV cert by
;  passing -Thumbprint to sign-dist.ps1; this .iss is unaffected.
; ============================================================================

#define MyAppName "nospacekey"
; MyAppVersion lives in version.iss (generated by scripts/sync-version.ps1) so the
; installer version stays in lockstep with the root Cargo.toml single source.
#include "version.iss"
#define MyAppPublisher "nospacekey プロジェクト参加者"

; --- Zenzai model download constants -------------------------------------
; REQUIRES Inno Setup 6.3.0+ : this file contains Japanese strings and is
; saved as UTF-8 WITHOUT a BOM, which older ISCC interprets as ANSI (mojibake).
; SINGLE SOURCE = crates/config/src/download.rs (MODEL_FILENAME / MODEL_URL /
; MODEL_SHA256). crates/config/tests/model_constants_consistency.rs asserts
; these three literals match; update BOTH files together or the test goes RED.
; The .gguf is fetched from the origin (HuggingFace) at install time and is
; NEVER bundled -- bundling would make this installer a CC-BY-SA-4.0
; redistributor (see docs/superpowers/specs/2026-07-16-installer-zenzai-
; download-design.md).
#define ModelFileName "ggml-model-Q5_K_M.gguf"
#define ModelDownloadURL "https://huggingface.co/Miwa-Keita/zenz-v3.1-small-gguf/resolve/main/ggml-model-Q5_K_M.gguf"
#define ModelSHA256 "4de930c06bef8c263aa1aa40684af206db4ce1b96375b3b8ed0ea508e0b14f6c"
#define CleanupScriptSHA256 GetSHA256OfFile("..\scripts\version-cleanup.ps1")
#define PreinstallRecoveryScriptName "nospacekey-preinstall-recovery.ps1"

[Setup]
; Fix the update identity. The current script has NO AppId (== AppName default),
; so pin AppId=nospacekey to match existing dev installs. Doing it before public
; distribution is the cheapest moment; if the naming decision later changes
; AppName, AppId can stay put -- that is the whole point of pinning it now.
AppId=nospacekey
AppName={#MyAppName}
AppVersion={#MyAppVersion}
; Windows VERSIONINFO accepts four numeric components, not SemVer prerelease text.
VersionInfoVersion={#MyAppFileVersion}
AppPublisher={#MyAppPublisher}
; Capture/restore is only deterministic when two upgrades cannot move the shared CLSID concurrently.
SetupMutex=nospacekey-tip-registration,Global\nospacekey-tip-registration
DefaultDirName={autopf}\nospacekey
UsePreviousAppDir=no
DisableDirPage=yes
DefaultGroupName=nospacekey
; TSF TIP registration is per-machine (HKLM) -> elevation required.
PrivilegesRequired=admin
; 64-bit only distribution (the TIP DLL and engine are x86_64).
ArchitecturesAllowed=x64compatible
ArchitecturesInstallIn64BitMode=x64compatible
LicenseFile=..\LICENSE
OutputBaseFilename=nospacekey-setup
Compression=lzma2
SolidCompression=yes
UninstallDisplayName=nospacekey 日本語入力
WizardStyle=modern
; The TIP DLL is held by every app that loaded the IME. Versioned paths make
; application-only restart sufficient and avoid Restart Manager entirely.
CloseApplications=no

[Languages]
Name: "japanese"; MessagesFile: "compiler:Languages\Japanese.isl"

[Tasks]
; Zenzai (neural conversion) opt-out download (~70 MB, from HuggingFace).
; Default-checked: settings default to zenzai.enabled=true and the engine
; auto-resolves the model beside the versioned engine (ZenzaiConfig.resolve), so
; placing the file is ALL that is needed -- no settings write, no toggle.
; Unchecked / offline / failed => classic conversion; the model can still be
; fetched later from the settings GUI (its LOCALAPPDATA + weight_path path).
Name: "zenzaimodel"; Description: "Zenzai（ニューラル変換）を使用する — 約70MBのモデルをダウンロード（推奨）"

[Files]
; Preflight must not depend on a possibly older recovery worker left by an
; interrupted install. Setup verifies this embedded copy while holding a handle
; that denies replacement, then uses it only before the normal file-copy phase.
Source: "..\scripts\version-cleanup.ps1"; DestName: "{#PreinstallRecoveryScriptName}"; Flags: dontcopy noencryption

; These root coordination artifacts survive a partial version-tree deletion.
; The gate keeps its file identity across upgrades; the trusted initializer
; migrates only the known beta.10 CRLF bytes while holding its byte-range lock.
Source: "task-transaction-gate"; DestDir: "{app}"; DestName: ".nospacekey-task-transaction"; Flags: onlyifdoesntexist uninsneveruninstall
Source: "..\scripts\version-cleanup.ps1"; DestDir: "{app}"; DestName: ".nospacekey-uninstall-recovery.ps1"; Flags: uninsneveruninstall

; The TIP registration moves to this release while already loaded DLLs continue
; executing from their older sibling directory.
Source: "..\dist\nospacekey_tip.dll"; DestDir: "{app}\versions\{#MyAppVersion}"; Flags: 64bit onlyifdoesntexist

; The matching engine is resolved relative to that exact loaded TIP DLL.
Source: "..\dist\NospacekeyEngineHost.exe"; DestDir: "{app}\versions\{#MyAppVersion}"; Flags: 64bit onlyifdoesntexist

; The checker keeps a dedicated entry so the wildcard cannot duplicate it.
Source: "..\dist\NospacekeyUpdateChecker.exe"; DestDir: "{app}\versions\{#MyAppVersion}"; Flags: 64bit onlyifdoesntexist

; Each engine gets its own complete app-local dependency closure. No file in an
; older version directory is touched during upgrade.
Source: "..\dist\*"; DestDir: "{app}\versions\{#MyAppVersion}"; Flags: recursesubdirs createallsubdirs onlyifdoesntexist; Excludes: "nospacekey_tip.dll,NospacekeyEngineHost.exe,NospacekeyUpdateChecker.exe"

[Dirs]
Name: "{app}\.nospacekey-uninstall"

[Icons]
; Shortcut to the settings GUI (SP6b) and to the third-party notices.
Name: "{group}\nospacekey 設定"; Filename: "{app}\versions\{#MyAppVersion}\NospacekeyConfig.exe"; AppUserModelID: "yachtida.nospacekey"
Name: "{group}\第三者ソフトウェアに関する通知"; Filename: "{app}\versions\{#MyAppVersion}\THIRD-PARTY-NOTICES.md"
Name: "{group}\nospacekey のアンインストール"; Filename: "{uninstallexe}"

[Registry]
; Minimal protocol activation: only the fixed update intent reaches Config's exact
; parser; arbitrary schemes/paths are ignored by the application.
Root: HKCR; Subkey: "nospacekey"; ValueType: string; ValueName: ""; ValueData: "URL:nospacekey プロトコル"; Flags: uninsdeletekey
Root: HKCR; Subkey: "nospacekey"; ValueType: string; ValueName: "URL Protocol"; ValueData: ""; Flags: uninsdeletevalue
Root: HKCR; Subkey: "nospacekey\DefaultIcon"; ValueType: string; ValueName: ""; ValueData: "{app}\versions\{#MyAppVersion}\NospacekeyConfig.exe,0"; Flags: uninsdeletekey
Root: HKCR; Subkey: "nospacekey\shell\open\command"; ValueType: string; ValueName: ""; ValueData: """{app}\versions\{#MyAppVersion}\NospacekeyConfig.exe"" ""%1"""; Flags: uninsdeletekey

[UninstallDelete]
; The Zenzai model is placed by [Code] (download), NOT by [Files], so the
; uninstaller does not track it. Without these lines a 70 MB .gguf survives
; uninstall and keeps the current version directory from being removed.
Type: files; Name: "{app}\versions\{#MyAppVersion}\models\{#ModelFileName}"
Type: dirifempty; Name: "{app}\versions\{#MyAppVersion}\models"
Type: dirifempty; Name: "{app}\versions\{#MyAppVersion}"

[Run]
; Move an existing automatic-check task to this version's checker even when the
; user does not open Settings after upgrading. runasoriginaluser avoids binding
; the task to a separate elevation credential. Silent/admin-only contexts may
; not have that token; old trees stay intact and each user's normal Config
; startup reconciliation repairs the task on their next launch.
Filename: "{app}\versions\{#MyAppVersion}\NospacekeyConfig.exe"; Parameters: "--repair-update-task"; Flags: runhidden waituntilterminated runasoriginaluser
; Runs elevated after installation and waits for SetupMutex in its own process. The
; worker is nowait so Setup can release the product-global registration gate first.
Filename: "{sys}\WindowsPowerShell\v1.0\powershell.exe"; Parameters: "{code:DeferredCleanupParameters}"; Flags: runhidden nowait; Check: ValidateCurrentCleanupPayload
; Optional: open the settings GUI right after install so the user can enable
; the external LLM / pick a model. Unchecked by default; skippable in silent.
Filename: "{app}\versions\{#MyAppVersion}\NospacekeyConfig.exe"; Description: "nospacekey の設定を開く"; Flags: postinstall nowait skipifsilent unchecked

[Code]
type
  TFileAttributeTagInfo = record
    FileAttributes: DWORD;
    ReparseTag: DWORD;
  end;

const
  CleanupFileReadAttributes = $00000080;
  CleanupGenericRead = $80000000;
  CleanupShareRead = $00000001;
  CleanupShareAll = $00000007;
  CleanupOpenExisting = 3;
  CleanupBackupSemantics = $02000000;
  CleanupOpenReparsePoint = $00200000;
  CleanupDirectoryAttribute = $00000010;
  CleanupReparseAttribute = $00000400;
  CleanupInvalidHandle = -1;

function CleanupCreateFile(const FileName: String; DesiredAccess, ShareMode: DWORD;
  SecurityAttributes: LongWord; CreationDisposition, FlagsAndAttributes: DWORD;
  TemplateFile: THandle): THandle;
external 'CreateFileW@kernel32.dll stdcall';

function CleanupGetFileInformationByHandleEx(FileHandle: THandle; InformationClass: Integer;
  var Information: TFileAttributeTagInfo; BufferSize: DWORD): BOOL;
external 'GetFileInformationByHandleEx@kernel32.dll stdcall';

function CleanupCloseHandle(Handle: THandle): BOOL;
external 'CloseHandle@kernel32.dll stdcall';

var
  DownloadPage: TDownloadWizardPage;
  // ssPostInstall へ「検証済みモデルが {tmp} に居る」ことを運ぶフラグ。
  // (タスク未選択・スキップ・失敗のとき ssPostInstall が {tmp} を触らないための門)
  ModelFetched: Boolean;
  ModelReusePath: String;
  PreviousInstall: Boolean;
  PreviousInstallRoot: String;
  PreviousInstallMetadataFailed: Boolean;
  PriorTipPath: String;
  PriorTipValidationFailed: Boolean;
  PriorRegistrationMarkerWritten: Boolean;
  NewTipRegistered: Boolean;
  InstallCompleted: Boolean;
  UninstallClaimed: Boolean;
  UninstallSentinelRestored: Boolean;
  UninstallStarted: Boolean;
  UninstallFinalized: Boolean;
  UninstallTipWasActive: Boolean;
  UninstallResumeDeleting: Boolean;
  InterruptedDeletingDetected: Boolean;

function TestNonReparsePath(const Path: String; ExpectDirectory: Boolean): Boolean;
var
  Handle: THandle;
  Information: TFileAttributeTagInfo;
  Flags: DWORD;
begin
  Result := False;
  Flags := CleanupOpenReparsePoint;
  if ExpectDirectory then
    Flags := Flags or CleanupBackupSemantics;
  Handle := CleanupCreateFile(Path, CleanupFileReadAttributes, CleanupShareAll,
    0, CleanupOpenExisting, Flags, 0);
  if Handle = CleanupInvalidHandle then
    Exit;
  try
    if not CleanupGetFileInformationByHandleEx(Handle, 9, Information,
        SizeOf(Information)) then
      Exit;
    if (Information.FileAttributes and CleanupReparseAttribute) <> 0 then
      Exit;
    Result := ((Information.FileAttributes and CleanupDirectoryAttribute) <> 0) =
      ExpectDirectory;
  finally
    CleanupCloseHandle(Handle);
  end;
end;

function OpenPinnedCleanupScript(const Path: String): THandle;
var
  Information: TFileAttributeTagInfo;
begin
  Result := CleanupCreateFile(Path, CleanupGenericRead, CleanupShareRead,
    0, CleanupOpenExisting, CleanupOpenReparsePoint, 0);
  if Result = CleanupInvalidHandle then
    Exit;
  if not CleanupGetFileInformationByHandleEx(Result, 9, Information,
      SizeOf(Information)) then begin
    CleanupCloseHandle(Result);
    Result := CleanupInvalidHandle;
    Exit;
  end;
  if ((Information.FileAttributes and CleanupDirectoryAttribute) <> 0) or
     ((Information.FileAttributes and CleanupReparseAttribute) <> 0) then begin
    CleanupCloseHandle(Result);
    Result := CleanupInvalidHandle;
  end;
end;

function PowerShellLiteral(const Value: String): String;
begin
  Result := Value;
  StringChangeEx(Result, '''', '''''', True);
  Result := '''' + Result + '''';
end;

function BuildCleanupBootstrapCommand(const Root, Tree, ScriptPath,
  Operation: String; AllowMissingTree, RequireSafeScriptAcl: Boolean): String;
var
  Paths: String;
  ScriptAclCheck: String;
begin
  Paths := '$paths=@($root);';
  if AllowMissingTree then
    Paths := Paths + 'if(Test-Path -LiteralPath $versions){$paths+=,$versions};'
  else
    Paths := Paths + '$paths+=,$versions;';
  if Tree <> '' then
    Paths := Paths + 'if(Test-Path -LiteralPath $tree){$paths+=,$tree};';
  if RequireSafeScriptAcl then
    ScriptAclCheck := ' -or -not (safe $script)'
  else
    ScriptAclCheck := '';
  Result :=
    '$ErrorActionPreference=''Stop'';' +
    '$root=' + PowerShellLiteral(Root) + ';$versions=Join-Path $root ''versions'';' +
    '$tree=' + PowerShellLiteral(Tree) + ';$script=' + PowerShellLiteral(ScriptPath) + ';' +
    '$trusted=@(''S-1-5-18'',''S-1-5-32-544'',''S-1-5-80-956008885-3418522649-1831038044-1853292631-2271478464'');' +
    '$bad=[int64]0x500D0156;' +
    'function sid($x){if($x -is [Security.Principal.SecurityIdentifier]){return $x.Value};' +
    'if($x -isnot [Security.Principal.IdentityReference]){$x=[Security.Principal.NTAccount]::new([string]$x)};' +
    'return $x.Translate([Security.Principal.SecurityIdentifier]).Value};' +
    'function safe($p){try{$a=Get-Acl -LiteralPath $p -ErrorAction Stop;' +
    'if($trusted -notcontains (sid $a.Owner)){return $false};' +
    'foreach($r in @($a.GetAccessRules($true,$true,[Security.Principal.SecurityIdentifier]))){' +
    'if($r.AccessControlType -ne [Security.AccessControl.AccessControlType]::Allow){continue};' +
    '$s=sid $r.IdentityReference;' +
    'if($s -ceq ''S-1-3-0'' -and ($r.PropagationFlags -band [Security.AccessControl.PropagationFlags]::InheritOnly)){continue};' +
    'if($trusted -notcontains $s -and ([int64]$r.FileSystemRights -band $bad)){return $false}};' +
    'return $true}catch{return $false}};' +
    Paths + 'foreach($p in @($paths)){$i=Get-Item -LiteralPath $p -Force -ErrorAction Stop;' +
    'if(-not $i.PSIsContainer -or ($i.Attributes -band [IO.FileAttributes]::ReparsePoint) -or -not (safe $p)){exit 21}};' +
    '$si=Get-Item -LiteralPath $script -Force -ErrorAction Stop;' +
    'if($si.PSIsContainer -or ($si.Attributes -band [IO.FileAttributes]::ReparsePoint)' + ScriptAclCheck + '){exit 22};' +
    '$pin=$null;$code=24;try{' +
    '$pin=[IO.FileStream]::new($script,[IO.FileMode]::Open,[IO.FileAccess]::Read,[IO.FileShare]::Read);' +
    'if((Get-FileHash -InputStream $pin -Algorithm SHA256).Hash -ine ''{#CleanupScriptSHA256}''){exit 23};' +
    '& $script -InstallRoot $root ' + Operation + ';$code=$LASTEXITCODE' +
    '}catch{$code=24}finally{if($null -ne $pin){$pin.Dispose()}};exit $code';
end;

function RunCleanupScript(const ScriptPath, Tree, Operation: String;
  AllowMissingTree, RequireSafeScriptAcl: Boolean; Wait: TExecWait;
  var ResultCode: Integer): Boolean;
var
  Root: String;
  Versions: String;
  Command: String;
  ScriptHandle: THandle;
  TreeExists: Boolean;
begin
  Result := False;
  Root := ExpandConstant('{app}');
  Versions := Root + '\versions';
  if not TestNonReparsePath(Root, True) then begin
    Log('Trusted cleanup rejected the install root path');
    Exit;
  end;
  TreeExists := (Tree <> '') and DirExists(Tree);
  if DirExists(Versions) then begin
    if not TestNonReparsePath(Versions, True) then begin
      Log('Trusted cleanup rejected the versions path');
      Exit;
    end;
  end else if not (AllowMissingTree and (not TreeExists)) then begin
    Log('Trusted cleanup requires the versions path');
    Exit;
  end;
  if Tree <> '' then begin
    if TreeExists then begin
      if not TestNonReparsePath(Tree, True) then begin
        Log('Trusted cleanup rejected the version tree path');
        Exit;
      end;
    end else if not AllowMissingTree then begin
      Log('Trusted cleanup requires the version tree path');
      Exit;
    end;
  end;
  ScriptHandle := OpenPinnedCleanupScript(ScriptPath);
  if ScriptHandle = CleanupInvalidHandle then begin
    Log('Trusted cleanup could not pin the script');
    Exit;
  end;
  try
    if CompareText(GetSHA256OfFile(ScriptPath), '{#CleanupScriptSHA256}') <> 0 then begin
      Log('Trusted cleanup rejected the script SHA256');
      Exit;
    end;
    Command := BuildCleanupBootstrapCommand(Root, Tree, ScriptPath, Operation,
      AllowMissingTree, RequireSafeScriptAcl);
    Result := Exec(ExpandConstant('{sys}\WindowsPowerShell\v1.0\powershell.exe'),
      '-NoProfile -NonInteractive -ExecutionPolicy Bypass -Command "' + Command + '"',
      '', SW_HIDE, Wait, ResultCode);
    if not Result then
      Log('Trusted cleanup could not start Windows PowerShell')
    else
      Log(Format('Trusted cleanup operation finished with exit code %d', [ResultCode]));
  finally
    CleanupCloseHandle(ScriptHandle);
  end;
end;

function RunTrustedCleanupScript(const ScriptPath, Tree, Operation: String;
  AllowMissingTree: Boolean; Wait: TExecWait; var ResultCode: Integer): Boolean;
begin
  Result := RunCleanupScript(ScriptPath, Tree, Operation, AllowMissingTree,
    True, Wait, ResultCode);
end;

function RunEmbeddedCleanupScript(const ScriptPath, Tree, Operation: String;
  AllowMissingTree: Boolean; Wait: TExecWait; var ResultCode: Integer): Boolean;
begin
  Result := RunCleanupScript(ScriptPath, Tree, Operation, AllowMissingTree,
    False, Wait, ResultCode);
end;

function DeferredCleanupParameters(Param: String): String;
var
  Root: String;
  Tree: String;
  ScriptPath: String;
begin
  Root := ExpandConstant('{app}');
  Tree := Root + '\versions\{#MyAppVersion}';
  ScriptPath := Tree + '\version-cleanup.ps1';
  Result := '-NoProfile -NonInteractive -ExecutionPolicy Bypass -Command "' +
    BuildCleanupBootstrapCommand(Root, Tree, ScriptPath, '', False, True) + '"';
end;

function ValidateCurrentCleanupPayload(): Boolean;
var
  Root: String;
  Tree: String;
  ScriptPath: String;
begin
  Root := ExpandConstant('{app}');
  Tree := Root + '\versions\{#MyAppVersion}';
  ScriptPath := Tree + '\version-cleanup.ps1';
  Result := TestNonReparsePath(Root, True) and
    TestNonReparsePath(Root + '\versions', True) and
    TestNonReparsePath(Tree, True) and
    TestNonReparsePath(ScriptPath, False) and
    (CompareText(GetSHA256OfFile(ScriptPath), '{#CleanupScriptSHA256}') = 0);
end;

function IsDigit(const C: Char): Boolean;
begin
  Result := (C >= '0') and (C <= '9');
end;

function IsNumericIdentifier(const Value: String): Boolean;
var
  I: Integer;
begin
  Result := Length(Value) > 0;
  if Result and (Length(Value) > 1) and (Value[1] = '0') then
    Result := False;
  for I := 1 to Length(Value) do
    if not IsDigit(Value[I]) then
      Result := False;
end;

function IsSemVerIdentifierList(const Value: String; RejectNumericLeadingZero: Boolean): Boolean;
var
  I: Integer;
  Start: Integer;
  Part: String;
  AllNumeric: Boolean;
begin
  Result := Length(Value) > 0;
  Start := 1;
  for I := 1 to Length(Value) + 1 do begin
    if (I > Length(Value)) or (Value[I] = '.') then begin
      Part := Copy(Value, Start, I - Start);
      if Length(Part) = 0 then begin
        Result := False;
        Exit;
      end;
      AllNumeric := True;
      for Start := 1 to Length(Part) do begin
        if not (IsDigit(Part[Start]) or
                ((Part[Start] >= 'A') and (Part[Start] <= 'Z')) or
                ((Part[Start] >= 'a') and (Part[Start] <= 'z')) or
                (Part[Start] = '-')) then begin
          Result := False;
          Exit;
        end;
        if not IsDigit(Part[Start]) then
          AllNumeric := False;
      end;
      if RejectNumericLeadingZero and AllNumeric and
         (Length(Part) > 1) and (Part[1] = '0') then begin
        Result := False;
        Exit;
      end;
      Start := I + 1;
    end;
  end;
end;

function IsStrictSemVer(const Value: String): Boolean;
var
  CoreAndPre: String;
  Core: String;
  Pre: String;
  Build: String;
  Dot1: Integer;
  Dot2: Integer;
  Sep: Integer;
begin
  Result := False;
  if (Length(Value) = 0) or (Value[1] = 'v') or (Value[1] = 'V') then
    Exit;
  Sep := Pos('+', Value);
  if Sep > 0 then begin
    CoreAndPre := Copy(Value, 1, Sep - 1);
    Build := Copy(Value, Sep + 1, Length(Value));
    if (Pos('+', Build) > 0) or not IsSemVerIdentifierList(Build, False) then
      Exit;
  end else
    CoreAndPre := Value;
  Sep := Pos('-', CoreAndPre);
  if Sep > 0 then begin
    Core := Copy(CoreAndPre, 1, Sep - 1);
    Pre := Copy(CoreAndPre, Sep + 1, Length(CoreAndPre));
    if not IsSemVerIdentifierList(Pre, True) then
      Exit;
  end else
    Core := CoreAndPre;
  Dot1 := Pos('.', Core);
  if Dot1 = 0 then
    Exit;
  Dot2 := Pos('.', Copy(Core, Dot1 + 1, Length(Core)));
  if Dot2 = 0 then
    Exit;
  Dot2 := Dot1 + Dot2;
  if Pos('.', Copy(Core, Dot2 + 1, Length(Core))) > 0 then
    Exit;
  Result := IsNumericIdentifier(Copy(Core, 1, Dot1 - 1)) and
            IsNumericIdentifier(Copy(Core, Dot1 + 1, Dot2 - Dot1 - 1)) and
            IsNumericIdentifier(Copy(Core, Dot2 + 1, Length(Core)));
end;

function NewTipPath(): String;
begin
  Result := ExpandConstant('{app}\versions\{#MyAppVersion}\nospacekey_tip.dll');
end;

function HasUnsafePathComponent(const Path: String): Boolean;
var
  I: Integer;
  Start: Integer;
  Part: String;
begin
  Result := False;
  Start := 4;
  for I := 4 to Length(Path) + 1 do begin
    if (I > Length(Path)) or (Path[I] = '\') then begin
      Part := Copy(Path, Start, I - Start);
      if (Part = '') or (Part = '.') or (Part = '..') or
         (Part[Length(Part)] = '.') or (Part[Length(Part)] = ' ') then begin
        Result := True;
        Exit;
      end;
      Start := I + 1;
    end;
  end;
end;

function NormalizeLocalInstallRoot(const Path: String): String;
var
  Candidate: String;
begin
  Result := '';
  Candidate := RemoveBackslashUnlessRoot(Path);
  if (Length(Candidate) < 4) or (Length(Candidate) > 1024) or
     (not (((Candidate[1] >= 'A') and (Candidate[1] <= 'Z')) or
           ((Candidate[1] >= 'a') and (Candidate[1] <= 'z')))) or
     (Candidate[2] <> ':') or (Candidate[3] <> '\') or
     (Pos('/', Candidate) > 0) or
     (Pos(':', Copy(Candidate, 3, Length(Candidate))) > 0) or
     HasUnsafePathComponent(Candidate) then
    Exit;
  if CompareText(ExpandFileName(Candidate), Candidate) <> 0 then
    Exit;
  Result := Candidate;
end;

function IsExpectedInstallPath(): Boolean;
var
  Actual: String;
  Expected: String;
begin
  Actual := NormalizeLocalInstallRoot(ExpandConstant('{app}'));
  Expected := NormalizeLocalInstallRoot(ExpandConstant('{autopf}\nospacekey'));
  Result := (Actual <> '') and (Expected <> '') and
            (CompareText(Actual, Expected) = 0);
end;

function LoadPreviousInstallRoot(): String;
var
  Candidate: String;
begin
  // {app} is deliberately the new fixed root, so legacy custom roots must come
  // from the exact prior AppId metadata before Inno replaces it.
  Result := '';
  PreviousInstallMetadataFailed := False;
  if not PreviousInstall then
    Exit;
  if not RegQueryStringValue(HKLM64,
       'Software\Microsoft\Windows\CurrentVersion\Uninstall\nospacekey_is1',
       'InstallLocation', Candidate) then begin
    PreviousInstallMetadataFailed := True;
    Exit;
  end;
  Result := NormalizeLocalInstallRoot(Candidate);
  if Result = '' then
    PreviousInstallMetadataFailed := True;
end;

function IsRetainedTipPath(const Path: String): Boolean;
var
  Legacy: String;
  VersionedRoot: String;
  Suffix: String;
  Version: String;
begin
  Result := False;
  if (not PreviousInstall) or (PreviousInstallRoot = '') or
     (Length(Path) > 4096) then
    Exit;
  Legacy := PreviousInstallRoot + '\nospacekey_tip.dll';
  if CompareText(Path, Legacy) = 0 then begin
    Result := FileExists(Path);
    Exit;
  end;
  VersionedRoot := PreviousInstallRoot + '\versions\';
  Suffix := '\nospacekey_tip.dll';
  Result := (Length(Path) > Length(VersionedRoot) + Length(Suffix)) and
            (CompareText(Copy(Path, 1, Length(VersionedRoot)), VersionedRoot) = 0) and
            (CompareText(Copy(Path, Length(Path) - Length(Suffix) + 1,
                              Length(Suffix)), Suffix) = 0);
  if not Result then
    Exit;
  Version := Copy(Path, Length(VersionedRoot) + 1,
                  Length(Path) - Length(VersionedRoot) - Length(Suffix));
  Result := IsStrictSemVer(Version) and
            (CompareText(Path, VersionedRoot + Version + Suffix) = 0) and FileExists(Path);
end;

function CapturePriorTipPath(): String;
var
  Candidate: String;
begin
  Result := '';
  PriorTipValidationFailed := False;
  if RegQueryStringValue(HKLM64,
       'SOFTWARE\Classes\CLSID\{B4B39227-EFF2-41DA-B357-0C3170A57875}\InprocServer32',
       '', Candidate) then begin
    if IsRetainedTipPath(Candidate) then
      Result := Candidate
    else
      PriorTipValidationFailed := True;
  end;
end;

function Utf16Hex(const Value: String): String;
var
  I: Integer;
begin
  Result := '';
  for I := 1 to Length(Value) do
    Result := Result + Format('%.4x', [Ord(Value[I])]);
end;

function WritePriorRegistrationMarker(): Boolean;
begin
  // The trusted new DLL independently constrains restore data to this elevated,
  // transaction-scoped root instead of trusting its command line alone.
  Result := RegWriteStringValue(HKLM64,
    'SOFTWARE\nospacekey\InstallerTransaction', 'PriorInstallRoot',
    PreviousInstallRoot);
  PriorRegistrationMarkerWritten := Result;
end;

function ClearPriorRegistrationMarker(): Boolean;
begin
  Result := True;
  if PriorRegistrationMarkerWritten then begin
    Result := RegWriteStringValue(HKLM64,
      'SOFTWARE\nospacekey\InstallerTransaction', 'PriorInstallRoot', '');
    if Result then begin
      if not RegDeleteValue(HKLM64, 'SOFTWARE\nospacekey\InstallerTransaction',
                           'PriorInstallRoot') then
        Log('TIP registration transaction marker was invalidated but not removed');
      RegDeleteKeyIfEmpty(HKLM64, 'SOFTWARE\nospacekey\InstallerTransaction');
      PriorRegistrationMarkerWritten := False;
    end else
      Log('Failed to invalidate TIP registration transaction marker');
  end;
end;

function RunNewTipRegistration(Unregister: Boolean): Boolean;
var
  Params: String;
  ExitCode: Integer;
begin
  if Unregister then
    Params := '/u /s "' + NewTipPath() + '"'
  else
    Params := '/s "' + NewTipPath() + '"';
  Result := Exec(ExpandConstant('{sys}\regsvr32.exe'), Params, '', SW_HIDE,
                 ewWaitUntilTerminated, ExitCode) and (ExitCode = 0);
end;

function RunTrustedTipRestore(const TargetPath: String): Boolean;
var
  Params: String;
  ExitCode: Integer;
begin
  Params := '/s /n /i:restore-utf16hex=' + Utf16Hex(TargetPath) +
            ' "' + NewTipPath() + '"';
  Result := Exec(ExpandConstant('{sys}\regsvr32.exe'), Params, '', SW_HIDE,
                 ewWaitUntilTerminated, ExitCode) and (ExitCode = 0);
end;

function TipRegistrationMatches(const ExpectedPath: String): Boolean;
var
  ActivePath: String;
  ThreadingModel: String;
begin
  Result := RegQueryStringValue(HKLM64,
       'SOFTWARE\Classes\CLSID\{B4B39227-EFF2-41DA-B357-0C3170A57875}\InprocServer32',
       '', ActivePath) and
    RegQueryStringValue(HKLM64,
       'SOFTWARE\Classes\CLSID\{B4B39227-EFF2-41DA-B357-0C3170A57875}\InprocServer32',
       'ThreadingModel', ThreadingModel) and
    (CompareText(ActivePath, ExpectedPath) = 0) and
    (CompareText(ThreadingModel, 'Apartment') = 0);
end;

function TipRegistrationIsAbsent(): Boolean;
begin
  Result := not RegValueExists(HKLM64,
       'SOFTWARE\Classes\CLSID\{B4B39227-EFF2-41DA-B357-0C3170A57875}\InprocServer32', '') and
    not RegValueExists(HKLM64,
       'SOFTWARE\Classes\CLSID\{B4B39227-EFF2-41DA-B357-0C3170A57875}\InprocServer32',
       'ThreadingModel');
end;

procedure RollbackTipRegistration();
begin
  if (PriorTipPath <> '') and IsRetainedTipPath(PriorTipPath) then begin
    Log('Restoring retained TIP registration: ' + PriorTipPath);
    if RunTrustedTipRestore(PriorTipPath) and TipRegistrationMatches(PriorTipPath) then
      NewTipRegistered := False
    else
      Log('Failed to restore retained TIP registration');
  end else begin
    Log('Removing failed fresh TIP registration');
    if RunNewTipRegistration(True) and TipRegistrationIsAbsent() then
      NewTipRegistered := False
    else
      Log('Failed to remove fresh TIP registration');
  end;
end;

procedure RegisterTipTransaction();
begin
  if (PriorTipPath <> '') and (not WritePriorRegistrationMarker()) then
    RaiseException('以前の日本語入力登録を安全に保持できないため、インストールを中止しました。');
  NewTipRegistered := True;
  if (not RunNewTipRegistration(False)) or
     (not TipRegistrationMatches(NewTipPath())) then begin
    RollbackTipRegistration();
    if NewTipRegistered then
      RaiseException('TIP の登録に失敗し、以前の登録も復元できませんでした。')
    else
      RaiseException('TIP の登録に失敗したため、インストールを取り消しました。');
  end;
end;

function IsCurrentTipActive(): Boolean;
var
  ActivePath: String;
begin
  Result := RegQueryStringValue(HKLM64,
       'SOFTWARE\Classes\CLSID\{B4B39227-EFF2-41DA-B357-0C3170A57875}\InprocServer32',
       '', ActivePath) and (CompareText(ActivePath, NewTipPath()) = 0);
end;

function SafeVersionName(const Name: String): Boolean;
var
  I: Integer;
begin
  Result := (Length(Name) > 0) and (Length(Name) <= 80);
  for I := 1 to Length(Name) do
    if not (((Name[I] >= '0') and (Name[I] <= '9')) or
            ((Name[I] >= 'A') and (Name[I] <= 'Z')) or
            ((Name[I] >= 'a') and (Name[I] <= 'z')) or
            (Name[I] = '.') or (Name[I] = '-') or (Name[I] = '+')) then
      Result := False;
end;

function ModelDestPath(): String;
begin
  Result := ExpandConstant('{app}\versions\{#MyAppVersion}\models\{#ModelFileName}');
end;

function FindReusableModel(): String;
var
  Root: String;
  Candidate: String;
  FindRec: TFindRec;
begin
  Result := '';
  Root := ExpandConstant('{app}\versions');
  if FindFirst(Root + '\*', FindRec) then begin
    try
      repeat
        if ((FindRec.Attributes and FILE_ATTRIBUTE_DIRECTORY) <> 0) and
           (FindRec.Name <> '.') and (FindRec.Name <> '..') and
           SafeVersionName(FindRec.Name) then begin
          Candidate := Root + '\' + FindRec.Name + '\models\{#ModelFileName}';
          if FileExists(Candidate) and
             (CompareText(GetSHA256OfFile(Candidate), '{#ModelSHA256}') = 0) then begin
            Result := Candidate;
            Exit;
          end;
        end;
      until not FindNext(FindRec);
    finally
      FindClose(FindRec);
    end;
  end;
end;

function QueryOriginalUserClsidOverlay(): Integer;
var
  Params: String;
  ExitCode: Integer;
begin
  // Elevated HKCU may belong to a different credential; query the interactive
  // user's hive before any machine-wide registration mutation.
  Params := '-NoProfile -NonInteractive -ExecutionPolicy Bypass -Command ' +
    '"try { $base = [Microsoft.Win32.RegistryKey]::OpenBaseKey(' +
    '[Microsoft.Win32.RegistryHive]::CurrentUser, ' +
    '[Microsoft.Win32.RegistryView]::Registry64); ' +
    '$overlay = $base.OpenSubKey(' +
    '''Software\Classes\CLSID\{B4B39227-EFF2-41DA-B357-0C3170A57875}'', $false); ' +
    'if ($null -ne $overlay) { $overlay.Dispose(); $base.Dispose(); exit 10 }; ' +
    '$base.Dispose(); exit 0 } catch { exit 20 }"';
  if ExecAsOriginalUser(
       ExpandConstant('{sys}\WindowsPowerShell\v1.0\powershell.exe'),
       Params, '', SW_HIDE, ewWaitUntilTerminated, ExitCode) then
    Result := ExitCode
  else
    Result := 30;
end;

function ValidateTaskTransactionArtifacts(): Boolean;
var
  ResultCode: Integer;
  RecoveryPath: String;
begin
  RecoveryPath := ExpandConstant('{app}\.nospacekey-uninstall-recovery.ps1');
  Result := RunTrustedCleanupScript(RecoveryPath, '',
    '-InitializeTaskTransactionArtifacts', False, ewWaitUntilTerminated, ResultCode) and
    (ResultCode = 0);
  if Result then
    Result := RunTrustedCleanupScript(RecoveryPath, '',
      '-RecoverInterruptedUninstalls', False, ewWaitUntilTerminated, ResultCode) and
      (ResultCode = 0);
end;

function RecoverInterruptedUninstallClaim(const RecoveryPath: String): Boolean;
var
  ResultCode: Integer;
  ActivePath: String;
  Tree: String;
begin
  Result := False;
  InterruptedDeletingDetected := False;
  if FileExists(ExpandConstant('{app}\.nospacekey-uninstall-recovery.ps1')) then begin
    if not RunEmbeddedCleanupScript(RecoveryPath, '',
        '-InitializeTaskTransactionArtifacts', False,
        ewWaitUntilTerminated, ResultCode) or (ResultCode <> 0) then
      Exit;
    if not RunEmbeddedCleanupScript(RecoveryPath, '',
        '-RecoverInterruptedUninstalls', False, ewWaitUntilTerminated, ResultCode) then
      Exit;
    if ResultCode = 3 then begin
      InterruptedDeletingDetected := True;
      Exit;
    end;
    if ResultCode <> 0 then
      Exit;
  end;
  Tree := ExpandConstant('{app}\versions\{#MyAppVersion}');
  if not DirExists(Tree) then begin
    Result := True;
    Exit;
  end;
  if FileExists(Tree + '\.nospacekey-lifetime.uninstalling') then begin
    if not RunTrustedCleanupScript(Tree + '\version-cleanup.ps1', Tree,
        '-RecoverUninstallClaim -UninstallBuild ''{#MyAppVersion}'' -DeadlineMs 15000',
        False, ewWaitUntilTerminated, ResultCode) or (ResultCode <> 0) then
      Exit;
  end;
  if not RegQueryStringValue(HKLM64,
      'SOFTWARE\Classes\CLSID\{B4B39227-EFF2-41DA-B357-0C3170A57875}\InprocServer32',
      '', ActivePath) then begin
    if not Exec(ExpandConstant('{sys}\regsvr32.exe'), '/s "' + NewTipPath() + '"',
        '', SW_HIDE, ewWaitUntilTerminated, ResultCode) or (ResultCode <> 0) then
      Exit;
  end;
  Result := True;
end;

function PrepareToInstall(var NeedsRestart: Boolean): String;
var
  OverlayStatus: Integer;
  RecoveryPath: String;
begin
  Result := '';
  if not IsExpectedInstallPath() then begin
    Result := 'インストール先を安全な固定場所として確認できないため、インストールを中止しました。';
    Exit;
  end;
  if PreviousInstallMetadataFailed then begin
    Result := '旧版のインストール場所を安全に確認できないため、インストールを中止しました。';
    Exit;
  end;
  try
    ExtractTemporaryFile('{#PreinstallRecoveryScriptName}');
  except
    Log('Failed to extract the embedded preinstall recovery worker: ' + GetExceptionMessage);
    Result := 'セットアップ内の復旧処理を安全に展開できないため、インストールを中止しました。';
    Exit;
  end;
  RecoveryPath := ExpandConstant('{tmp}\{#PreinstallRecoveryScriptName}');
  if not RecoverInterruptedUninstallClaim(RecoveryPath) then begin
    if InterruptedDeletingDetected then
      Result := '中断した同じバージョンのアンインストーラーを再実行して、アンインストールを完了してください。'
    else
      Result := '中断されたアンインストールを安全に復旧できないため、インストールを中止しました。';
    Exit;
  end;
  if DirExists(ExpandConstant('{app}\versions\{#MyAppVersion}')) then
    Result := '同じバージョンの製品ファイルがすでに存在するため、安全に上書きできません。別バージョンのインストーラーを使用してください。';
  if Result <> '' then
    Exit;
  PriorTipPath := CapturePriorTipPath();
  if PriorTipValidationFailed then begin
    Result := '現在の日本語入力登録を安全な旧版として確認できないため、インストールを中止しました。';
    Exit;
  end;
  OverlayStatus := QueryOriginalUserClsidOverlay();
  if OverlayStatus = 10 then
    Result := '現在のユーザーに競合する日本語入力登録があるため、インストールを中止しました。'
  else if OverlayStatus <> 0 then begin
    Result := '現在のユーザーの日本語入力登録を確認できないため、インストールを中止しました。';
  end;
end;

procedure InitializeWizard();
begin
  PreviousInstall := RegKeyExists(
    HKLM64,
    'Software\Microsoft\Windows\CurrentVersion\Uninstall\nospacekey_is1');
  PreviousInstallRoot := LoadPreviousInstallRoot();
  DownloadPage := CreateDownloadPage(SetupMessage(msgWizardPreparing), SetupMessage(msgPreparingDesc), nil);
  DownloadPage.ShowBaseNameInsteadOfUrl := True;
end;

function NextButtonClick(CurPageID: Integer): Boolean;
begin
  Result := True;
  // wpReady 時点なら {app} は確定済み(ディレクトリ選択ページ通過後 / 更新時はレジストリ解決)。
  // 既存モデルがあれば再取得しない(更新インストールで 70MB を引き直さない)。
  if (CurPageID = wpReady) and WizardIsTaskSelected('zenzaimodel')
     and (not FileExists(ModelDestPath())) then begin
    ModelReusePath := FindReusableModel();
    if ModelReusePath <> '' then begin
      Log('Reusing verified Zenzai model from ' + ModelReusePath);
      Result := True;
      Exit;
    end;
    DownloadPage.Clear;
    DownloadPage.Add('{#ModelDownloadURL}', '{#ModelFileName}', '{#ModelSHA256}');
    DownloadPage.Show;
    try
      try
        // DownloadTemporaryFile が SHA256 を検証(不一致は例外)。保存先は {tmp}。
        DownloadPage.Download;
        ModelFetched := True;
      except
        // 非致命: 従来変換で続行。silent では Suppressible が既定応答(IDOK)で流れる。
        // ユーザー自身の Abort に「失敗しました」ダイアログを重ねない(ログのみ)。
        if DownloadPage.AbortedByUser then
          Log('Zenzai model download aborted by user.')
        else begin
          Log('Zenzai model download failed: ' + GetExceptionMessage);
          SuppressibleMsgBox(
            'Zenzai モデルのダウンロードに失敗しました。従来変換でインストールを続行します。'
            + #13#10 + 'モデルは後から nospacekey 設定画面（変換エンジン）で取得できます。',
            mbInformation, MB_OK, IDOK);
        end;
      end;
    finally
      DownloadPage.Hide;
    end;
  end;
end;

procedure CurStepChanged(CurStep: TSetupStep);
begin
  // ssPostInstall = [Files] 展開後なので版別 models\ (dist の README.txt で作成済み) が実在。
  // ForceDirectories は dist 構成が変わっても DL 成功分を黙って捨てないための保険。
  // {tmp} 経由の 2 段構えにより、失敗時に {app} へ半端ファイルが残ることはない。
  if (CurStep = ssPostInstall) and ModelFetched then begin
    ForceDirectories(ExpandConstant('{app}\versions\{#MyAppVersion}\models'));
    if not CopyFile(ExpandConstant('{tmp}\{#ModelFileName}'), ModelDestPath(), False) then
      Log('Zenzai model copy to versioned models directory failed');
  end;
  if (CurStep = ssPostInstall) and (ModelReusePath <> '') then begin
    ForceDirectories(ExpandConstant('{app}\versions\{#MyAppVersion}\models'));
    if not CopyFile(ModelReusePath, ModelDestPath(), True) then
      Log('Verified Zenzai model reuse failed');
  end;
  if (CurStep = ssPostInstall) and (not ValidateCurrentCleanupPayload()) then
    RaiseException('版別クリーンアップ処理の配置を安全に確認できませんでした。');
  if (CurStep = ssPostInstall) and (not ValidateTaskTransactionArtifacts()) then
    RaiseException('更新タスクの安全な調整領域を確認できませんでした。');
  if CurStep = ssPostInstall then
    RegisterTipTransaction();
  if (CurStep = ssPostInstall) and PreviousInstall and (not WizardSilent) then
    SuppressibleMsgBox(
      'すでに nospacekey を使用中のアプリは旧版を使い続けます。' + #13#10
      + 'アプリを再起動すると新版に切り替わります。Windows の再起動は不要です。' + #13#10
      + '学習履歴は安全のためバージョンごとに分離され、新版では新しく蓄積されます。',
      mbInformation, MB_OK, IDOK);
  if CurStep = ssDone then begin
    if not ClearPriorRegistrationMarker() then
      RaiseException('日本語入力登録の一時情報を安全に消去できませんでした。');
    InstallCompleted := True;
  end;
end;

procedure DeinitializeSetup();
begin
  if NewTipRegistered and (not InstallCompleted) then
    RollbackTipRegistration();
  if not ClearPriorRegistrationMarker() then
    Log('TIP registration transaction marker remains after Setup termination');
end;

function RestoreUninstallClaim(): Boolean;
var
  ResultCode: Integer;
  SentinelPath: String;
  ClaimedPath: String;
begin
  Result := False;
  if not UninstallClaimed then begin
    Result := True;
    Exit;
  end;
  SentinelPath := ExpandConstant('{app}\versions\{#MyAppVersion}\.nospacekey-lifetime');
  ClaimedPath := SentinelPath + '.uninstalling';
  if not UninstallSentinelRestored then begin
    if not RenameFile(ClaimedPath, SentinelPath) then begin
      Log('Failed to restore version lifetime sentinel after cancelled uninstall');
      Exit;
    end;
    UninstallSentinelRestored := True;
  end;
  if UninstallTipWasActive then begin
    if not Exec(ExpandConstant('{sys}\regsvr32.exe'),
        '/s "' + ExpandConstant('{app}\versions\{#MyAppVersion}\nospacekey_tip.dll') + '"',
        '', SW_HIDE, ewWaitUntilTerminated, ResultCode) or (ResultCode <> 0) or
        (not IsCurrentTipActive()) then begin
      Log('Failed to restore TIP registration after cancelled uninstall');
      Exit;
    end;
  end;
  UninstallClaimed := False;
  Result := True;
end;

function ValidateDeletingUninstallResume(): Integer;
var
  ResultCode: Integer;
  RecoveryPath: String;
begin
  Result := 3;
  RecoveryPath := ExpandConstant('{app}\.nospacekey-uninstall-recovery.ps1');
  if FileExists(RecoveryPath) then begin
    if not RunTrustedCleanupScript(RecoveryPath,
        ExpandConstant('{app}\versions\{#MyAppVersion}'),
        '-ValidateDeletingUninstall -UninstallBuild ''{#MyAppVersion}''',
        True, ewWaitUntilTerminated, ResultCode) then begin
      Result := 2;
    end else begin
      Result := ResultCode;
    end;
  end;
end;

function InitializeUninstall(): Boolean;
var
  ResumeValidation: Integer;
  ResultCode: Integer;
  SentinelPath: String;
begin
  Result := False;
  UninstallClaimed := False;
  UninstallSentinelRestored := False;
  UninstallStarted := False;
  UninstallFinalized := False;
  UninstallResumeDeleting := False;
  ResumeValidation := ValidateDeletingUninstallResume();
  if ResumeValidation = 0 then begin
      if IsCurrentTipActive() then begin
        SuppressibleMsgBox('中断したアンインストールの日本語入力登録が残っているため、アンインストールを中止します。',
          mbError, MB_OK, IDOK);
        Exit;
      end;
      UninstallResumeDeleting := True;
      UninstallStarted := True;
      Result := True;
      Exit;
  end;
  if ResumeValidation <> 3 then begin
    SuppressibleMsgBox('中断したアンインストールの状態を安全に確認できないため、アンインストールを中止します。',
      mbError, MB_OK, IDOK);
    Exit;
  end;
  UninstallTipWasActive := IsCurrentTipActive();

  if FileExists(ExpandConstant('{app}\versions\{#MyAppVersion}\NospacekeyConfig.exe')) then
    Exec(ExpandConstant('{app}\versions\{#MyAppVersion}\NospacekeyConfig.exe'),
      '--stop-engine', '', SW_HIDE, ewWaitUntilTerminated, ResultCode);

  if UninstallTipWasActive then begin
    if not Exec(ExpandConstant('{sys}\regsvr32.exe'),
        '/u /s "' + ExpandConstant('{app}\versions\{#MyAppVersion}\nospacekey_tip.dll') + '"',
        '', SW_HIDE, ewWaitUntilTerminated, ResultCode) or (ResultCode <> 0) then begin
      SuppressibleMsgBox('日本語入力の登録解除に失敗したため、アンインストールを中止します。',
        mbError, MB_OK, IDOK);
      Exit;
    end;
  end;

  if not RunTrustedCleanupScript(
      ExpandConstant('{app}\versions\{#MyAppVersion}\version-cleanup.ps1'),
      ExpandConstant('{app}\versions\{#MyAppVersion}'),
      '-ClaimForUninstall -UninstallBuild ''{#MyAppVersion}'' -DeadlineMs 15000',
      False, ewWaitUntilTerminated, ResultCode) or (ResultCode <> 0) then begin
    if UninstallTipWasActive then begin
      SentinelPath := ExpandConstant('{app}\versions\{#MyAppVersion}\.nospacekey-lifetime');
      if FileExists(SentinelPath) then begin
        UninstallClaimed := True;
        UninstallSentinelRestored := True;
        if not RestoreUninstallClaim() then
          Log('Failed to restore TIP registration after uninstall claim failure');
      end else
        Log('Uninstall claim failed with no canonical sentinel; refusing to reactivate an interrupted deleting tree');
    end;
    SuppressibleMsgBox('nospacekey を使用中のアプリを閉じてから、もう一度アンインストールしてください。',
      mbError, MB_OK, IDOK);
    Exit;
  end;
  UninstallClaimed := True;
  UninstallSentinelRestored := False;
  Result := True;
end;

function CommitUninstallTasks(): Boolean;
var
  ResultCode: Integer;
begin
  Result := RunTrustedCleanupScript(
    ExpandConstant('{app}\versions\{#MyAppVersion}\version-cleanup.ps1'),
    ExpandConstant('{app}\versions\{#MyAppVersion}'),
    '-CommitUninstallTasks -UninstallBuild ''{#MyAppVersion}''',
    False, ewWaitUntilTerminated, ResultCode) and (ResultCode = 0);
end;

function FinalizeUninstallTasks(): Boolean;
var
  ResultCode: Integer;
begin
  Result := RunTrustedCleanupScript(
    ExpandConstant('{app}\.nospacekey-uninstall-recovery.ps1'),
    ExpandConstant('{app}\versions\{#MyAppVersion}'),
    '-FinalizeUninstallTasks -UninstallBuild ''{#MyAppVersion}''',
    True, ewWaitUntilTerminated, ResultCode) and (ResultCode = 0);
end;

procedure CurUninstallStepChanged(CurUninstallStep: TUninstallStep);
begin
  if CurUninstallStep = usUninstall then begin
    if UninstallResumeDeleting and (ValidateDeletingUninstallResume() <> 0) then
      RaiseException('削除直前の安全確認に失敗したため、中断したアンインストールを再開できません。');
    if (not UninstallResumeDeleting) and (not CommitUninstallTasks()) then begin
      if FileExists(ExpandConstant('{app}\versions\{#MyAppVersion}\.nospacekey-lifetime')) then begin
        UninstallSentinelRestored := True;
        if not RestoreUninstallClaim() then
          RaiseException('更新タスクの削除失敗後に日本語入力の状態を復旧できませんでした。');
      end else begin
        Log('Task commit failed without a fully restored canonical sentinel; retaining the inert uninstall claim');
        UninstallClaimed := False;
      end;
      RaiseException('更新タスクを安全に削除できなかったため、アンインストールを中止します。');
    end;
    UninstallStarted := True;
  end;
  if CurUninstallStep = usDone then begin
    if not FinalizeUninstallTasks() then
      RaiseException('アンインストール完了情報を安全に確定できませんでした。');
    UninstallFinalized := True;
  end;
end;

procedure DeinitializeUninstall();
var
  ResultCode: Integer;
  RecoveryPath: String;
begin
  if UninstallClaimed and (not UninstallStarted) and (not RestoreUninstallClaim()) then begin
    SuppressibleMsgBox('アンインストール中止後に日本語入力の状態を復旧できませんでした。',
      mbError, MB_OK, IDOK);
    Exit;
  end;
  if not UninstallFinalized then
    Exit;

  RecoveryPath := ExpandConstant('{app}\.nospacekey-uninstall-recovery.ps1');
  if not RunTrustedCleanupScript(RecoveryPath,
      ExpandConstant('{app}\versions\{#MyAppVersion}'),
      '-ValidateFinalUninstallArtifacts -ExpectedRecoverySha256 ''{#CleanupScriptSHA256}''',
      True, ewWaitUntilTerminated, ResultCode) or (ResultCode <> 0) then begin
    Log('Final uninstall artifacts were not safe to remove; retaining them for diagnosis and retry');
    Exit;
  end;
  if not DeleteFile(RecoveryPath) then begin
    Log('Failed to delete the validated uninstall recovery script; retaining its dependencies');
    Exit;
  end;
  if not RemoveDir(ExpandConstant('{app}\.nospacekey-uninstall')) then
    Log('Failed to delete the empty uninstall transaction directory');
  if DirExists(ExpandConstant('{app}\versions')) and
      (not RemoveDir(ExpandConstant('{app}\versions'))) then
    Log('Failed to delete the empty versions directory');
  if not DeleteFile(ExpandConstant('{app}\.nospacekey-task-transaction')) then
    Log('Failed to delete the validated task transaction gate');
  if DirExists(ExpandConstant('{app}')) and (not RemoveDir(ExpandConstant('{app}'))) then
    Log('The install root still contains files owned by the uninstaller or retained diagnostics');
end;
