; AUTO-GENERATED by scripts/sync-version.ps1 -- do not edit by hand.
; The source of truth is [workspace.package] version in the root Cargo.toml.
#define MyAppVersion "1.7.0-beta.2"
#define MyAppFileVersion "1.7.0.0"
