; AUTO-GENERATED by scripts/sync-version.ps1 -- do not edit by hand.
; The source of truth is [workspace.package] version in the root Cargo.toml.
#define MyAppVersion "1.2.2-beta.5.1"
#define MyAppVersionNum "1.2.2.0"
